### ISSUE TITLE
Consider splitting Ansible output on newlines

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#110]
Right now, the output we get from Ansible is a big JSON blob that is not split on newlines, and is hard to read.  Can we consider a way to split on newlines so that the output is easier to read?  One implementation goes like so:

`debug: var=service_swarm_err_output.stdout.split('\n')`

Certainly this is not useful for *all* output, but should we spend some time to find a way to apply this globally?

**Comment by greg-hellings** [comment]
With newer versions of Ansible (2.4+) having the `yaml` stdout callback, this is no longer necessary.
