### ISSUE TITLE
Fedora 25 test in Travis fails consistently

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#111]
Example:  https://travis-ci.org/RedHatQE/cinch/jobs/231461426

**Comment by tehsmyers** [comment]
I took a quick guess at what might be going on with no luck: https://github.com/RedHatQE/cinch/pull/112

**Comment by greg-hellings** [comment]
I've removed the test for now. It's a failure specific to the Travis CI environment, so we'll handle Fedora testing elsewhere.
