### ISSUE TITLE
Determine why spurious changes reported in plugins

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#117]
Regardless of the number of times it is run, the plugin installation process always reports at least some of the plug ins have been changed. Track down the reasons for this and mitigate, if possible (might require a PR to upstream Ansible to update the module - if this is the case, the patched version can live in our library/ folder until we upgrade to a version of Ansible that includes the fix).

**Comment by robled** [comment]
In some unrelated testing, I am no longer able to reproduce this problem after several test runs.  All the existing plugins report unchanged.  Do you think we may be able to close this out?

**Comment by greg-hellings** [comment]
Aren't we pinning all plugins now? That should circumvent the triggering scenario. It's also possible the upstream module has been updated. I'm happy with closing this out since it, at the least, hasn't affected us in a while.
