### ISSUE TITLE
Provide configurable ntp server option

### ISSUE THREAD

**Issue by scottlinux** [RedHatQE/cinch#135]
Hello, 

Relevant to my interests would be a way to specify an ntp server to optionally use in lieu of distro defaults.

Some configurable (but not required) var action to specify an ntp server would be awesome.

![great](https://user-images.githubusercontent.com/2176591/27652247-08ff2c96-5c09-11e7-8101-3bf42daaef74.png)

**Comment by greg-hellings** [comment]
I believe that @jpaulovic has this on his radar, as it is relevant to his interests as well. If you have the time and skill for a PR, we'd be happy to include that in the NTP role.

**Comment by scottlinux** [comment]
Thanks - I'll submit a PR for review.
