### ISSUE TITLE
Allow the jenkins RPM package to be unpinned for version upgrades

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#152]
By default, cinch blacklists the jenkins RPM package from being upgraded via /etc/yum.conf:

https://github.com/RedHatQE/cinch/blob/master/cinch/roles/jenkins_master/defaults/main.yml#L143

For the use case of upgrades, we should be able to temporarily remove this setting to allow the upgrade to complete, and then blacklist the package upgrade again afterwards.

**Comment by greg-hellings** [comment]
Addressed in #154
