### ISSUE TITLE
Improve error handling for groovy scripts

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#158]
Right now the groovy scripts usually fail with a message similar to 

`{"failed": true, "msg": "The conditional check 'script_output.output.find('CHANGED') != -1' failed. The error was: error while evaluating conditional (script_output.output.find('CHANGED') != -1): 'dict object' has no attribute 'output'"}`

Ideally we should try to capture the traceback and present it to the user to aid in debugging.

**Comment by greg-hellings** [comment]
Done via #159
