### ISSUE TITLE
Allow IP addresses to be used in the Ansible inventory

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#180]
Ansible Tower/AWX has some limitations when it comes to hostname length, and for these cases we would like to supply an IP address in the inventory, but continue to use the actual hostname for places in our playbooks that require it.

**Comment by robled** [comment]
@jpaulovic - Is this still required or do more recent versions of Ansible Tower/AWX that we have access to resolve this issue?

**Comment by jpaulovic** [comment]
I don't recall coming across this issue in the past several months, so let's just close it for now...
