### ISSUE TITLE
Verify that 'repositories' variable in the 'repositories' role can be used as intended

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#196]
I received a report that this functionality did not work as intended, in that if the empty (by default) 'repositories' variable is overridden via Ansible group_vars, the 'repositories' role will skip over that input data, with no error produced via Ansible.  I was able to reproduce this problem in preliminary testing.  I'll test this again and provide more details on the scenario.

**Comment by robled** [comment]
After further testing and discussion, it seems likely that variable precedence of group_vars included with cinch in the **jenkins_slave** role are overriding inputs given by users via the _all_ group_vars file.  Given that the use case here is highly likely that we want to append additional repos, we should resolve it in that way, which would mean extending the **repositories** role to allow for this.

**Comment by robled** [comment]
@greg-hellings - was this resolved here?

https://github.com/RedHatQE/cinch/pull/198

**Comment by greg-hellings** [comment]
Let's just say "yes" and roll with it. I'm pretty sure this is what prompted that changeset.
