### ISSUE TITLE
Consider adding retries to problematic Travis build steps

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#203]
It's common for our Travi CI builds to fail due to intermittent infrastructure issues.  We should identify problematic build steps and consider adding some retries so that humans don't have to manually restart builds:

https://docs.travis-ci.com/user/common-build-problems/#Timeouts-installing-dependencies

**Comment by greg-hellings** [comment]
I've added travis_retry to the install script. Are there any other steps that you think we should retry? Should retry the tests, just because they sometimes do weird things?
