### ISSUE TITLE
Group vars from cinch repo can't be overriden by custom inventory group_vars

### ISSUE THREAD

**Issue by jpaulovic** [RedHatQE/cinch#210]
Because of the precedence rules in Ansible it is impossible to override group_vars defined in this repo by a custom set from a different inventory. This makes it impossible to use upstream cinch without any modifications and source the group_vars from a different (downstream) repo containing inventory file and group / host vars. 
I guess a possible solution might be to rename the group_vars directory to something that would indicate it's just a set of example/recommended values and just leave some sane values in each role's defaults.

**Comment by robled** [comment]
After further discussion, we have learned this is likely an issue with Ansible Tower/AWX and we've agreed to look in that direction.  It's a bit of a long story and not worth repeating here, but the group_vars support in cinch is working as intended.
