### ISSUE TITLE
Firewall updates

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#23]
Ensure the iptables has the following rules:

* Accept all ICMP
* Accept all loopback
* Reject outgoing connections to 127.* that are not on loopback
* Allow inbound SSH
* Accept related and established connections
* Allow inbound TCP port 50000 for Jenkins slaves
* Allow inbound TCP port 8888 for ZeroMQ

Drop/deny everything else.

**Comment by greg-hellings** [comment]
Existing rules should be cleared out and replaced with this.

Additional rules should be added immediately before the drop/deny to do port opening/redirection for 80 and 443 based on HTTPS configuration.

**Comment by jpaulovic** [comment]
I believe all the rules were implemented in #95 , we will remove the port forwarding when dealing with #32 / #88 .

**Comment by greg-hellings** [comment]
Per @jpaulovic's comment and PRs, I'm closing this issue out.
