### ISSUE TITLE
Jenkins master provisioning is broken in release version 1.1.0 - create a new release

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#237]
This issue has been [resolved](https://github.com/RedHatQE/cinch/commit/84ef41374dad28180e53c471851833b9d26557c4), but a new release version needs to be made.

**Comment by greg-hellings** [comment]
A new release should be able to be made once #236 is resolved. Once reviews are completed on that, it should be as easy as pushing a tag with the appropriate name. Can that PR get some love so that this issue can also be resolved?

**Comment by robled** [comment]
@abraverm - Can you assist with the PR review and subsequent release version?

**Comment by abraverm** [comment]
once the PR will be fixed and merged I will release 1.1.1

**Comment by scottlinux** [comment]
It's a fairly good size update, I think @greg-hellings had already specified 1.2.0 in #236

**Comment by abraverm** [comment]
ok

**Comment by abraverm** [comment]
done

**Comment by robled** [comment]
I'm not seeing the new release on pypi - was it pushed there?

https://redhatqe-cinch.readthedocs.io/en/latest/maintainers.html

**Comment by greg-hellings** [comment]
1.1.0 never made it to PyPI, either. I had made a mental note to look into why but hadn't gotten around to it. I see now why. The `.travis.yml` file has the following conditional:
```yaml
     on:¬
       tags: true¬
       condition: $TEST = lint.sh¬
```

Sometime between 1.0.0 and 1.1.0 we changed the tests to tox, so `$TEST = lint.sh` has never been satisfied. That line needs to, instead, read `$TOXENV = lint`. I'll make a PR for that, but 1.1.0 and 1.2.0 should be pushed manually to PyPI in the interim.

**Comment by greg-hellings** [comment]
#238 will address this in the future. However, manual copies of it should be pushed for now. @abraverm - do you want to do that, or would you like for me to?

**Comment by abraverm** [comment]
@greg-hellings I need admin rights over the project in PyPI, can you add me?

**Comment by abraverm** [comment]
1.1.0 and 1.2.0 were uploaded and released, thanks for the help @greg-hellings
