### ISSUE TITLE
LDAP/Kerberos

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#24]
If the host is configured for LDAP/Kerberos, add the same set of authentication to Jenkins.

Also, provide a method to configure the host for LDAP/Kerberos authentication.

**Comment by abraverm** [comment]
I think those are different issues and should be handled separately.

**Comment by greg-hellings** [comment]
If that's true, go ahead and split this, or open a second issue. I don't know enough about either LDAP or Kerberos to know how integrated or separate they are.

**Comment by greg-hellings** [comment]
LDAP is now handled. Kerberos will need to be addressed by a different issue.
