### ISSUE TITLE
Jenkins Service User

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#25]
Ensure that Jenkins Service User is properly created and has SSH keys generated.

**Comment by jpaulovic** [comment]
"...and has SSH keys generated." - is there any reason for uploading a pre-generated SSH private key to the hosts in jenkins_common role instead of generating the whole keypair directly on the host?

**Comment by greg-hellings** [comment]
In private discussions we addressed why an SSH key might need to be uploaded. This is now handled, and the user's SSH keys are appropriately installed.
