### ISSUE TITLE
Fix Inspec error in CI

### ISSUE THREAD

**Issue by abraverm** [RedHatQE/cinch#252]
Tests are failing on  `/home/travis/build/RedHatQE/cinch/scripts/master.sh: line 52: inspec: command not found` even though it was installed succesfully.

**Comment by greg-hellings** [comment]
Can you link to a build that's failing that way? I'm seeing failures seemingly related to the actual CentOS image being used with the message `"Failed to list units: Failed to activate service 'org.freedesktop.systemd1': timed out"`

**Comment by abraverm** [comment]
https://travis-ci.org/RedHatQE/cinch/jobs/531344653

**Comment by abraverm** [comment]
BTW, same problem: https://travis-ci.org/RedHatQE/jenkins-profile/builds/531565143
