### ISSUE TITLE
(1) Run JJB

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#29]
Create a method of running JJB on a configured git repository of jobs against configured Jenkins masters.

**Comment by tehsmyers** [comment]
Feedback indicated that this is not really important to consumers, so a reasonable solution might be to add a "how-to" to the docs for this instead of doing it by default.

**Comment by robled** [comment]
Is a "how-to" even needed?  I feel that this is standard manual Jenkins admin stuff.
