### ISSUE TITLE
Configure Swarm Port

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#31]
Configure Jenkins Master to listen on port 50000 for slaves, instead of relying on the default ports.

**Comment by greg-hellings** [comment]
#101 configures this for masters. Have you tested that slaves can still connect?

**Comment by jpaulovic** [comment]
I have tested the deployment of both master and slave in one playbook run, after which I could see the slave listed in the master under 'Build Executor Status' with a message saying 'Connected via JNLP agent'. I didn't do any other additional checks.
