### ISSUE TITLE
Add yamllint to tests

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#45]

**Comment by greg-hellings** [comment]
Will yamllint give us something better that the current ansible-playbook --syntax-check call does not?

**Comment by robled** [comment]
The main thing I would like to check for is consistent spacing in YAML.  Does **ansible-playbook --syntax-check** do that?  Also, how do you feel about having '---' on the first line of all YAML files?  This seems pretty standard and I know yamllint will check for that too.

**Comment by greg-hellings** [comment]
I don't believe it addresses style guide stuff, only actual syntax violations.

Also, I avoid the triple dash completely, as it seems completely superfluous - I've never had a file fail to parse without it. And YAML seems pretty well targeted towards avoiding unnecessary typing. Does it actually serve any purpose?

**Comment by robled** [comment]
Yeah, the triple dash isn't that big of a deal and I wouldn't worry about that.  But I do think that consistent spacing and style in YAML is important and if yamllint can give us that I would be in favor of adding it to our tests.
