### ISSUE TITLE
Compatibility issues with jenkins 2?

### ISSUE THREAD

**Issue by jjanco** [RedHatQE/cinch#48]
My playbook.yml:
- hosts: default
  vars:
    some certificates and repositories hidden
    gcc_compat_package: compat-gcc-44
    jenkins_rpm: jenkins
    jenkins_ssl_cert: cinch/vagrant/master_ssl/jenkins.crt
    jenkins_ssl_key: cinch/vagrant/master_ssl/jenkins.key
    jenkins_security_enabled: true
  roles:
    - certificate_authority
    - repositories
    - jenkins_common
    - jenkins_master

Test machine: centOs7
jenkins_rpm ~ jenkins-2.32

First error:
TASK [jenkins_master : download jenkins CLI] ***********************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /var/lib/jenkins not writable"}

Workaround with permissions 777

Errors about configuring users:

TASK [jenkins_master : configure CLI users appropriately] **********************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Roles not found - have you configured an admin using the Role-based Authorization Strategy?"}

Workaround with  jenkins_security_enabled: false

Errors about plugins:
TASK [jenkins_master : install plugins] ****************************************
FAILED - RETRYING: TASK: jenkins_master : install plugins (3 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (2 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (1 retries left).
failed: [default] (item=build-name-setter) => {"attempts": 3, "details": "HTTP Error 403: Forbidden", "failed": true, "item": "build-name-setter", "msg": "Cannot get CSRF"}
FAILED - RETRYING: TASK: jenkins_master : install plugins (3 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (2 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (1 retries left).
failed: [default] (item=envinject) => {"attempts": 3, "details": "HTTP Error 403: Forbidden", "failed": true, "item": "envinject", "msg": "Cannot get CSRF"}
FAILED - RETRYING: TASK: jenkins_master : install plugins (3 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (2 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (1 retries left).
failed: [default] (item=greenballs) => {"attempts": 3, "details": "HTTP Error 403: Forbidden", "failed": true, "item": "greenballs", "msg": "Cannot get CSRF"}
FAILED - RETRYING: TASK: jenkins_master : install plugins (3 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (2 retries left).
FAILED - RETRYING: TASK: jenkins_master : install plugins (1 retries left).
failed: [default] (item=rebuild) => {"attempts": 3, "details": "HTTP Error 403: Forbidden", "failed": true, "item": "rebuild", "msg": "Cannot get CSRF"}

**Comment by greg-hellings** [comment]
We do not, yet, support Jenkins 2. We are just beginning to work out the idea of moving to it. For now, we only support the Jenkins 1.6x series.

**Comment by jjanco** [comment]
Do you have some time plan, about  migrating to jenkins2?

**Comment by kubco2** [comment]
First error was about some misconfiguration of my ansible scripts ... after executing your vagrant sample, it didnt pop up.

**Comment by greg-hellings** [comment]
@jjanco Can you test this now, with @kubco2's patch merged in?

**Comment by greg-hellings** [comment]
This is now working, and will be released with version 0.8.0.
