### ISSUE TITLE
cinchpin command may be using an incorrect path for the linch-pin inventory directory

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#62]
**linchpin init** as of right now in the master branch creates a subdirectory named **inventories**, yet cinchpin expects the directory to be named **inventory**.

**Comment by tehsmyers** [comment]
yoink

**Comment by tehsmyers** [comment]
It looks like cinch is following the docs, but the [linchpin docs](http://linch-pin.readthedocs.io/en/latest/config_general.html) are wrong. The actual dir is indeed inventories:

https://github.com/CentOS-PaaS-SIG/linch-pin/blob/develop/linchpin/__init__.py#L24

So I think I'll fix up cinch, and then follow up with a linchpin docs PR. The other dirs (layouts, topologies) are plural, so at least from the outside looking in the name "inventories" appears to be semantically correct.

**Comment by tehsmyers** [comment]
This is the related linchpin docs PR for the develop branch:
https://github.com/CentOS-PaaS-SIG/linch-pin/pull/205

**Comment by tehsmyers** [comment]
And for completeness, it's worth pointing out that the behavior is [the same](https://github.com/CentOS-PaaS-SIG/linch-pin/blob/v0.9.1/linchpin.py#L85-L87) in the latest linchpin release, so 0.9.1 is consistent with what's on develop.
