### ISSUE TITLE
Remove beaker-project repo where possible

### ISSUE THREAD

**Issue by greg-hellings** [RedHatQE/cinch#70]
There are now beaker-client RPMs built into Fedora and EPEL7 repositories. Therefore, remove the beaker-project.org repository files from those groups and use the native packages, instead.

**Comment by tehsmyers** [comment]
This is implicit in the issue description, but just to be explicit: the referenced PR (#77) does not remove these repositories from el6 hosts since the required beaker packages are provided by EPEL 7, but *not* EPEL 6.
